<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report - {{ $report['report_type'] }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-radius: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 28px;
        }
        .header p {
            margin: 5px 0 0;
            opacity: 0.9;
        }
        .info-box {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            border-left: 4px solid #667eea;
        }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            margin-bottom: 30px;
        }
        .summary-card {
            background: white;
            padding: 15px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            border: 1px solid #e0e0e0;
        }
        .summary-card h3 {
            margin: 0 0 5px;
            font-size: 14px;
            color: #666;
            text-transform: uppercase;
        }
        .summary-card .value {
            font-size: 24px;
            font-weight: bold;
            color: #667eea;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        th {
            background: #667eea;
            color: white;
            padding: 12px;
            text-align: left;
            font-size: 14px;
        }
        td {
            padding: 10px 12px;
            border-bottom: 1px solid #e0e0e0;
            font-size: 13px;
        }
        tr:nth-child(even) {
            background: #f8f9fa;
        }
        .section-title {
            font-size: 18px;
            color: #333;
            margin: 25px 0 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #667eea;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
            font-size: 12px;
            color: #999;
        }
        .status-badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 11px;
            font-weight: bold;
        }
        .status-accepted { background: #d4edda; color: #155724; }
        .status-declined { background: #f8d7da; color: #721c24; }
        .status-pending { background: #fff3cd; color: #856404; }
        .status-rejected { background: #f8d7da; color: #721c24; }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>JOB PORTAL REPORT</h1>
        <p>{{ ucfirst($report['report_type']) }} Report</p>
    </div>

    <!-- Report Info -->
    <div class="info-box">
        <strong>Report Type:</strong> {{ ucfirst($report['report_type']) }}<br>
        <strong>Period:</strong> {{ $report['period']['from'] }} to {{ $report['period']['to'] }}<br>
        <strong>Generated At:</strong> {{ $report['generated_at'] }}<br>
        <strong>Generated By:</strong> {{ $report['generated_by'] }}
    </div>

    <!-- Summary -->
    <h2 class="section-title">SUMMARY</h2>
    <div class="summary-grid">
        <div class="summary-card">
            <h3>New Societies</h3>
            <div class="value">{{ $report['summary']['new_societies'] }}</div>
        </div>
        <div class="summary-card">
            <h3>Total Societies</h3>
            <div class="value">{{ $report['summary']['total_societies'] }}</div>
        </div>
        <div class="summary-card">
            <h3>New Validations</h3>
            <div class="value">{{ $report['summary']['new_validations'] }}</div>
        </div>
        <div class="summary-card">
            <h3>Validations Completed</h3>
            <div class="value">{{ $report['summary']['validations_completed'] }}</div>
        </div>
        <div class="summary-card">
            <h3>Acceptance Rate</h3>
            <div class="value">{{ $report['summary']['validation_acceptance_rate'] }}</div>
        </div>
        <div class="summary-card">
            <h3>Pending Validations</h3>
            <div class="value">{{ $report['summary']['validations_pending'] }}</div>
        </div>
        <div class="summary-card">
            <h3>New Applications</h3>
            <div class="value">{{ $report['summary']['new_applications'] }}</div>
        </div>
        <div class="summary-card">
            <h3>Applications Accepted</h3>
            <div class="value">{{ $report['summary']['applications_accepted'] }}</div>
        </div>
        <div class="summary-card">
            <h3>Applications Rejected</h3>
            <div class="value">{{ $report['summary']['applications_rejected'] }}</div>
        </div>
        <div class="summary-card">
            <h3>Active Job Vacancies</h3>
            <div class="value">{{ $report['summary']['active_job_vacancies'] }}</div>
        </div>
    </div>

    <!-- Validations by Status -->
    <h2 class="section-title">VALIDATIONS BY STATUS</h2>
    <table>
        <thead>
            <tr>
                <th>Status</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><span class="status-badge status-pending">PENDING</span></td>
                <td>{{ $report['details']['validations_by_status']['pending'] }}</td>
            </tr>
            <tr>
                <td><span class="status-badge status-accepted">ACCEPTED</span></td>
                <td>{{ $report['details']['validations_by_status']['accepted'] }}</td>
            </tr>
            <tr>
                <td><span class="status-badge status-declined">DECLINED</span></td>
                <td>{{ $report['details']['validations_by_status']['declined'] }}</td>
            </tr>
        </tbody>
    </table>

    <!-- Applications by Status -->
    <h2 class="section-title">APPLICATIONS BY STATUS</h2>
    <table>
        <thead>
            <tr>
                <th>Status</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><span class="status-badge status-pending">PENDING</span></td>
                <td>{{ $report['details']['applications_by_status']['pending'] }}</td>
            </tr>
            <tr>
                <td><span class="status-badge status-accepted">ACCEPTED</span></td>
                <td>{{ $report['details']['applications_by_status']['accepted'] }}</td>
            </tr>
            <tr>
                <td><span class="status-badge status-rejected">REJECTED</span></td>
                <td>{{ $report['details']['applications_by_status']['rejected'] }}</td>
            </tr>
        </tbody>
    </table>

    <!-- Top Job Categories -->
    @if(count($report['details']['top_job_categories']) > 0)
    <h2 class="section-title">TOP JOB CATEGORIES</h2>
    <table>
        <thead>
            <tr>
                <th>Category</th>
                <th>Total Validations</th>
            </tr>
        </thead>
        <tbody>
            @foreach($report['details']['top_job_categories'] as $category)
            <tr>
                <td>{{ $category->job_category }}</td>
                <td>{{ $category->validations_count }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <!-- Top Companies -->
    @if(count($report['details']['top_companies']) > 0)
    <h2 class="section-title">TOP COMPANIES BY APPLICATIONS</h2>
    <table>
        <thead>
            <tr>
                <th>Company</th>
                <th>Total Applications</th>
            </tr>
        </thead>
        <tbody>
            @foreach($report['details']['top_companies'] as $company)
            <tr>
                <td>{{ $company->company }}</td>
                <td>{{ $company->job_apply_societies_count }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <!-- New Societies -->
    @if(count($report['details']['new_societies_list']) > 0)
    <h2 class="section-title">NEW SOCIETIES</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>ID Card Number</th>
                <th>Gender</th>
                <th>Regional</th>
                <th>Registered</th>
            </tr>
        </thead>
        <tbody>
            @foreach($report['details']['new_societies_list'] as $society)
            <tr>
                <td>{{ $society->name }}</td>
                <td>{{ $society->id_card_number }}</td>
                <td>{{ ucfirst($society->gender) }}</td>
                <td>{{ $society->regional->district ?? '' }}, {{ $society->regional->province ?? '' }}</td>
                <td>{{ $society->created_at->format('d M Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>This report was automatically generated by Job Portal System</p>
        <p>© {{ date('Y') }} Job Portal - All Rights Reserved</p>
    </div>
</body>
</html>
